[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Example Enemy for Lethal Company."
websiteUrl = "https://github.com/Hamunii/LC-ExampleEnemy"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/LethalInternship.dll"
target = "plugins/Szumi57-LethalInternship/"

[[build.copy]]
source = "../../UnityProject/AssetBundles/StandaloneWindows/modassets"
target = "plugins/Szumi57-LethalInternship/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]