namespace LethalInternship.SharedAbstractions.Enums
{
    public enum EnumInputAction
    {
        None = 0,
        FollowMe,
        StayHere,
        PointToAction,
        SetToAutoFlee,
        SetToAutoDefense,
        DropItem,
        DropAllItems,
        GoToShip,
        SetGatheringPoint,
        GoToGatheringPoint,
        RemoveGatheringPoint,
        GoToVehicle,
        ScavengeToShip,
        ScavengeToGatheringPoint,
        ScavengeToCruiser,
        PreviousSuit,
        NextSuit,
        SameSuit,
        RandomSuit,
        SelectSuit,
        Close,
        ReturnToAll,
        PreviousIntern,
        NextIntern,
        UnloadCruiser,
        UnloadGatheringPoint,
        DropAllItemsInShip,
        DropAllItemsOnGatheringPoint,
        DropAllItemsInCruiser,
        SwapWeapon,
        ActivateItem,
    }
}
