namespace LethalInternship.SharedAbstractions.Enums
{
    public enum GameAction
    {
        Look,
        Move,
        Jump,
        Sprint,
        //OpenMenu,
        //Interact,
        Crouch,
        Use,
        //ActivateItem,
        //Discard,
        //SwitchItem,
        //QEItemInteract,
        //EnableChat,
        //SubmitChat,
        //ReloadBatteries,
        //SetFreeCamera,
        //InspectItem,
        //SpeedCheat,
        //PingScan,
        //VoiceButton,
        //Emote1,
        //Emote2,
        //BuildMode,
        //ConfirmBuildMode,
        //Delete,
        //ItemSecondaryUse,
        //ItemTertiaryUse
    }
}
